services:
  django:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/code
    ports:
      - 8000:8000

    command: /bin/bash -c "/bin/bash /code/django_entrypoint.sh"
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5